# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: backend

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # Maximum 1 pod will be stopped during updating
      maxSurge: 2         # Create maximum 2 pods during updating
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nahidacunny/backend:latest
        ports:
        - containerPort: 9000

---
# Backend service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: backend
