# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: frontend

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # Maximum 1 pod will be stopped during updating
      maxSurge: 2         # Create maximum 2 pods during updating
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nahidacunny/frontend:latest
        ports:
        - containerPort: 3000

---
# Frontend service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend
