# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: netflix-app

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app-deployment
  namespace: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # Maximum 1 pod will be stopped during updating
      maxSurge: 2         # Create maximum 2 pods during updating
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: nahidacunny/netflix:latest
        ports:
        - containerPort: 80

---
# Backend service
apiVersion: v1
kind: Service
metadata:
  name: netflix-app-service
  namespace: netflix-app
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: netflix-app
